/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReconciliationRouteImport } from './routes/reconciliation'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupShopsNewRouteImport } from './routes/setup/shops/new'
import { Route as SetupRoutesNewRouteImport } from './routes/setup/routes/new'
import { Route as SetupEmployeesNewRouteImport } from './routes/setup/employees/new'
import { Route as SetupShopsIdEditRouteImport } from './routes/setup/shops/$id.edit'
import { Route as SetupShopsIdBalanceRouteImport } from './routes/setup/shops/$id.balance'
import { Route as SetupRoutesIdEditRouteImport } from './routes/setup/routes/$id.edit'
import { Route as SetupEmployeesIdEditRouteImport } from './routes/setup/employees/$id.edit'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationRoute = ReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupShopsNewRoute = SetupShopsNewRouteImport.update({
  id: '/shops/new',
  path: '/shops/new',
  getParentRoute: () => SetupRoute,
} as any)
const SetupRoutesNewRoute = SetupRoutesNewRouteImport.update({
  id: '/routes/new',
  path: '/routes/new',
  getParentRoute: () => SetupRoute,
} as any)
const SetupEmployeesNewRoute = SetupEmployeesNewRouteImport.update({
  id: '/employees/new',
  path: '/employees/new',
  getParentRoute: () => SetupRoute,
} as any)
const SetupShopsIdEditRoute = SetupShopsIdEditRouteImport.update({
  id: '/shops/$id/edit',
  path: '/shops/$id/edit',
  getParentRoute: () => SetupRoute,
} as any)
const SetupShopsIdBalanceRoute = SetupShopsIdBalanceRouteImport.update({
  id: '/shops/$id/balance',
  path: '/shops/$id/balance',
  getParentRoute: () => SetupRoute,
} as any)
const SetupRoutesIdEditRoute = SetupRoutesIdEditRouteImport.update({
  id: '/routes/$id/edit',
  path: '/routes/$id/edit',
  getParentRoute: () => SetupRoute,
} as any)
const SetupEmployeesIdEditRoute = SetupEmployeesIdEditRouteImport.update({
  id: '/employees/$id/edit',
  path: '/employees/$id/edit',
  getParentRoute: () => SetupRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/operations': typeof OperationsRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reports': typeof ReportsRoute
  '/setup': typeof SetupRouteWithChildren
  '/stats': typeof StatsRoute
  '/setup/employees/new': typeof SetupEmployeesNewRoute
  '/setup/routes/new': typeof SetupRoutesNewRoute
  '/setup/shops/new': typeof SetupShopsNewRoute
  '/setup/employees/$id/edit': typeof SetupEmployeesIdEditRoute
  '/setup/routes/$id/edit': typeof SetupRoutesIdEditRoute
  '/setup/shops/$id/balance': typeof SetupShopsIdBalanceRoute
  '/setup/shops/$id/edit': typeof SetupShopsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/operations': typeof OperationsRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reports': typeof ReportsRoute
  '/setup': typeof SetupRouteWithChildren
  '/stats': typeof StatsRoute
  '/setup/employees/new': typeof SetupEmployeesNewRoute
  '/setup/routes/new': typeof SetupRoutesNewRoute
  '/setup/shops/new': typeof SetupShopsNewRoute
  '/setup/employees/$id/edit': typeof SetupEmployeesIdEditRoute
  '/setup/routes/$id/edit': typeof SetupRoutesIdEditRoute
  '/setup/shops/$id/balance': typeof SetupShopsIdBalanceRoute
  '/setup/shops/$id/edit': typeof SetupShopsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/operations': typeof OperationsRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reports': typeof ReportsRoute
  '/setup': typeof SetupRouteWithChildren
  '/stats': typeof StatsRoute
  '/setup/employees/new': typeof SetupEmployeesNewRoute
  '/setup/routes/new': typeof SetupRoutesNewRoute
  '/setup/shops/new': typeof SetupShopsNewRoute
  '/setup/employees/$id/edit': typeof SetupEmployeesIdEditRoute
  '/setup/routes/$id/edit': typeof SetupRoutesIdEditRoute
  '/setup/shops/$id/balance': typeof SetupShopsIdBalanceRoute
  '/setup/shops/$id/edit': typeof SetupShopsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/operations'
    | '/reconciliation'
    | '/reports'
    | '/setup'
    | '/stats'
    | '/setup/employees/new'
    | '/setup/routes/new'
    | '/setup/shops/new'
    | '/setup/employees/$id/edit'
    | '/setup/routes/$id/edit'
    | '/setup/shops/$id/balance'
    | '/setup/shops/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/operations'
    | '/reconciliation'
    | '/reports'
    | '/setup'
    | '/stats'
    | '/setup/employees/new'
    | '/setup/routes/new'
    | '/setup/shops/new'
    | '/setup/employees/$id/edit'
    | '/setup/routes/$id/edit'
    | '/setup/shops/$id/balance'
    | '/setup/shops/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/operations'
    | '/reconciliation'
    | '/reports'
    | '/setup'
    | '/stats'
    | '/setup/employees/new'
    | '/setup/routes/new'
    | '/setup/shops/new'
    | '/setup/employees/$id/edit'
    | '/setup/routes/$id/edit'
    | '/setup/shops/$id/balance'
    | '/setup/shops/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  OperationsRoute: typeof OperationsRoute
  ReconciliationRoute: typeof ReconciliationRoute
  ReportsRoute: typeof ReportsRoute
  SetupRoute: typeof SetupRouteWithChildren
  StatsRoute: typeof StatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation': {
      id: '/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof ReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/shops/new': {
      id: '/setup/shops/new'
      path: '/shops/new'
      fullPath: '/setup/shops/new'
      preLoaderRoute: typeof SetupShopsNewRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/routes/new': {
      id: '/setup/routes/new'
      path: '/routes/new'
      fullPath: '/setup/routes/new'
      preLoaderRoute: typeof SetupRoutesNewRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/employees/new': {
      id: '/setup/employees/new'
      path: '/employees/new'
      fullPath: '/setup/employees/new'
      preLoaderRoute: typeof SetupEmployeesNewRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/shops/$id/edit': {
      id: '/setup/shops/$id/edit'
      path: '/shops/$id/edit'
      fullPath: '/setup/shops/$id/edit'
      preLoaderRoute: typeof SetupShopsIdEditRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/shops/$id/balance': {
      id: '/setup/shops/$id/balance'
      path: '/shops/$id/balance'
      fullPath: '/setup/shops/$id/balance'
      preLoaderRoute: typeof SetupShopsIdBalanceRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/routes/$id/edit': {
      id: '/setup/routes/$id/edit'
      path: '/routes/$id/edit'
      fullPath: '/setup/routes/$id/edit'
      preLoaderRoute: typeof SetupRoutesIdEditRouteImport
      parentRoute: typeof SetupRoute
    }
    '/setup/employees/$id/edit': {
      id: '/setup/employees/$id/edit'
      path: '/employees/$id/edit'
      fullPath: '/setup/employees/$id/edit'
      preLoaderRoute: typeof SetupEmployeesIdEditRouteImport
      parentRoute: typeof SetupRoute
    }
  }
}

interface SetupRouteChildren {
  SetupEmployeesNewRoute: typeof SetupEmployeesNewRoute
  SetupRoutesNewRoute: typeof SetupRoutesNewRoute
  SetupShopsNewRoute: typeof SetupShopsNewRoute
  SetupEmployeesIdEditRoute: typeof SetupEmployeesIdEditRoute
  SetupRoutesIdEditRoute: typeof SetupRoutesIdEditRoute
  SetupShopsIdBalanceRoute: typeof SetupShopsIdBalanceRoute
  SetupShopsIdEditRoute: typeof SetupShopsIdEditRoute
}

const SetupRouteChildren: SetupRouteChildren = {
  SetupEmployeesNewRoute: SetupEmployeesNewRoute,
  SetupRoutesNewRoute: SetupRoutesNewRoute,
  SetupShopsNewRoute: SetupShopsNewRoute,
  SetupEmployeesIdEditRoute: SetupEmployeesIdEditRoute,
  SetupRoutesIdEditRoute: SetupRoutesIdEditRoute,
  SetupShopsIdBalanceRoute: SetupShopsIdBalanceRoute,
  SetupShopsIdEditRoute: SetupShopsIdEditRoute,
}

const SetupRouteWithChildren = SetupRoute._addFileChildren(SetupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  OperationsRoute: OperationsRoute,
  ReconciliationRoute: ReconciliationRoute,
  ReportsRoute: ReportsRoute,
  SetupRoute: SetupRouteWithChildren,
  StatsRoute: StatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
