/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSetupRouteImport } from './routes/_authed/setup'
import { Route as AuthedReportsRouteImport } from './routes/_authed/reports'
import { Route as AuthedReconciliationRouteImport } from './routes/_authed/reconciliation'
import { Route as AuthedOperationsRouteImport } from './routes/_authed/operations'
import { Route as AuthedInvoicesRouteImport } from './routes/_authed/invoices'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSetupRoute = AuthedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReconciliationRoute = AuthedReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOperationsRoute = AuthedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInvoicesRoute = AuthedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/invoices': typeof AuthedInvoicesRoute
  '/operations': typeof AuthedOperationsRoute
  '/reconciliation': typeof AuthedReconciliationRoute
  '/reports': typeof AuthedReportsRoute
  '/setup': typeof AuthedSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/invoices': typeof AuthedInvoicesRoute
  '/operations': typeof AuthedOperationsRoute
  '/reconciliation': typeof AuthedReconciliationRoute
  '/reports': typeof AuthedReportsRoute
  '/setup': typeof AuthedSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/invoices': typeof AuthedInvoicesRoute
  '/_authed/operations': typeof AuthedOperationsRoute
  '/_authed/reconciliation': typeof AuthedReconciliationRoute
  '/_authed/reports': typeof AuthedReportsRoute
  '/_authed/setup': typeof AuthedSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/invoices'
    | '/operations'
    | '/reconciliation'
    | '/reports'
    | '/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/invoices'
    | '/operations'
    | '/reconciliation'
    | '/reports'
    | '/setup'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/dashboard'
    | '/_authed/invoices'
    | '/_authed/operations'
    | '/_authed/reconciliation'
    | '/_authed/reports'
    | '/_authed/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/setup': {
      id: '/_authed/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthedSetupRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reconciliation': {
      id: '/_authed/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof AuthedReconciliationRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/operations': {
      id: '/_authed/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthedOperationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/invoices': {
      id: '/_authed/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthedInvoicesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedInvoicesRoute: typeof AuthedInvoicesRoute
  AuthedOperationsRoute: typeof AuthedOperationsRoute
  AuthedReconciliationRoute: typeof AuthedReconciliationRoute
  AuthedReportsRoute: typeof AuthedReportsRoute
  AuthedSetupRoute: typeof AuthedSetupRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedInvoicesRoute: AuthedInvoicesRoute,
  AuthedOperationsRoute: AuthedOperationsRoute,
  AuthedReconciliationRoute: AuthedReconciliationRoute,
  AuthedReportsRoute: AuthedReportsRoute,
  AuthedSetupRoute: AuthedSetupRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
