/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSetupRouteRouteImport } from './routes/_authed/setup/route'
import { Route as AuthedReportsRouteRouteImport } from './routes/_authed/reports/route'
import { Route as AuthedReconciliationRouteRouteImport } from './routes/_authed/reconciliation/route'
import { Route as AuthedOperationsRouteRouteImport } from './routes/_authed/operations/route'
import { Route as AuthedInvoicesRouteRouteImport } from './routes/_authed/invoices/route'
import { Route as AuthedDashboardRouteRouteImport } from './routes/_authed/dashboard/route'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSetupRouteRoute = AuthedSetupRouteRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsRouteRoute = AuthedReportsRouteRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReconciliationRouteRoute =
  AuthedReconciliationRouteRouteImport.update({
    id: '/reconciliation',
    path: '/reconciliation',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedOperationsRouteRoute = AuthedOperationsRouteRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInvoicesRouteRoute = AuthedInvoicesRouteRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRouteRoute = AuthedDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRouteRoute
  '/invoices': typeof AuthedInvoicesRouteRoute
  '/operations': typeof AuthedOperationsRouteRoute
  '/reconciliation': typeof AuthedReconciliationRouteRoute
  '/reports': typeof AuthedReportsRouteRoute
  '/setup': typeof AuthedSetupRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRouteRoute
  '/invoices': typeof AuthedInvoicesRouteRoute
  '/operations': typeof AuthedOperationsRouteRoute
  '/reconciliation': typeof AuthedReconciliationRouteRoute
  '/reports': typeof AuthedReportsRouteRoute
  '/setup': typeof AuthedSetupRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRouteRoute
  '/_authed/invoices': typeof AuthedInvoicesRouteRoute
  '/_authed/operations': typeof AuthedOperationsRouteRoute
  '/_authed/reconciliation': typeof AuthedReconciliationRouteRoute
  '/_authed/reports': typeof AuthedReportsRouteRoute
  '/_authed/setup': typeof AuthedSetupRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/invoices'
    | '/operations'
    | '/reconciliation'
    | '/reports'
    | '/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/invoices'
    | '/operations'
    | '/reconciliation'
    | '/reports'
    | '/setup'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_authed/dashboard'
    | '/_authed/invoices'
    | '/_authed/operations'
    | '/_authed/reconciliation'
    | '/_authed/reports'
    | '/_authed/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/setup': {
      id: '/_authed/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthedSetupRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reconciliation': {
      id: '/_authed/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof AuthedReconciliationRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/operations': {
      id: '/_authed/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthedOperationsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/invoices': {
      id: '/_authed/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthedInvoicesRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRouteRoute: typeof AuthedDashboardRouteRoute
  AuthedInvoicesRouteRoute: typeof AuthedInvoicesRouteRoute
  AuthedOperationsRouteRoute: typeof AuthedOperationsRouteRoute
  AuthedReconciliationRouteRoute: typeof AuthedReconciliationRouteRoute
  AuthedReportsRouteRoute: typeof AuthedReportsRouteRoute
  AuthedSetupRouteRoute: typeof AuthedSetupRouteRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRouteRoute: AuthedDashboardRouteRoute,
  AuthedInvoicesRouteRoute: AuthedInvoicesRouteRoute,
  AuthedOperationsRouteRoute: AuthedOperationsRouteRoute,
  AuthedReconciliationRouteRoute: AuthedReconciliationRouteRoute,
  AuthedReportsRouteRoute: AuthedReportsRouteRoute,
  AuthedSetupRouteRoute: AuthedSetupRouteRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
